version: '3.9'

services:
  db:
    image: postgres:15
    container_name: hackathon-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: hackathon-backend
    command: ./start-backend.sh
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres_data:
